function(microcrt_sources)
  set(target microcrt_c)
  set(sources ${ARGN})

  if(sources)
    list(GET sources 0 first_arg)
    if(TARGET ${first_arg})
      set(target ${first_arg})
      list(REMOVE_AT sources 0)
    endif()
  endif()

  get_property(current_sources TARGET ${target} PROPERTY SOURCES)
  set(final_new_sources "")

  foreach(source IN LISTS sources)
    get_filename_component(source_base "${source}" NAME_WLE)
    get_filename_component(source_ext "${source}" EXT)
    set(should_add TRUE)
    set(to_remove "")

    foreach(current IN LISTS current_sources)
      get_filename_component(current_base "${current}" NAME_WLE)
      get_filename_component(current_ext "${current}" EXT)

      if("${source_base}" STREQUAL "${current_base}")
        if("${source_ext}" STREQUAL ".S" AND "${current_ext}" STREQUAL ".c")
          list(APPEND to_remove "${current}")
          set(should_add TRUE)
        elseif("${source_ext}" STREQUAL ".c" AND "${current_ext}" STREQUAL ".S")
          set(should_add FALSE)
        else()
          set(should_add FALSE)
        endif()
        break()
      endif()
    endforeach()

    if(to_remove)
      get_property(sources_tmp TARGET ${target} PROPERTY SOURCES)
      list(REMOVE_ITEM sources_tmp ${to_remove})
      set_property(TARGET ${target} PROPERTY SOURCES "${sources_tmp}")
      set(current_sources ${sources_tmp})
    endif()

    if(should_add)
      list(APPEND final_new_sources "${source}")
    endif()
  endforeach()

  if(final_new_sources)
    target_sources(${target} PRIVATE ${final_new_sources})
  endif()

  set(MICROCRT_LAST_ADDED_SOURCES ${final_new_sources} PARENT_SCOPE)
endfunction()

function(microcrt_sources_flags)
  set(target microcrt_c)
  set(args ${ARGN})

  if(args)
    list(GET args 0 first_arg)
    if(TARGET ${first_arg})
      set(target ${first_arg})
      list(REMOVE_AT args 0)
    endif()
  endif()

  set(local_flags "")
  set(local_sources "")
  set(parsing_flags TRUE)
  foreach(arg IN LISTS args)
    if(parsing_flags AND (arg MATCHES "\\.(c|S|s|cpp|cxx)$"))
      set(parsing_flags FALSE)
    endif()
    if(parsing_flags)
      list(APPEND local_flags ${arg})
    else()
      list(APPEND local_sources ${arg})
    endif()
  endforeach()

  microcrt_sources(${target} ${local_sources})
  set(newly_added ${MICROCRT_LAST_ADDED_SOURCES})

  if(newly_added AND local_flags AND NOT local_flags STREQUAL "0")
    foreach(src ${newly_added})
      get_filename_component(abs_src "${src}" ABSOLUTE)
      set_source_files_properties("${abs_src}"
        TARGET_DIRECTORY ${target}
        PROPERTIES COMPILE_OPTIONS "${local_flags}")
    endforeach()
  endif()
endfunction()
